In [1]:
import tehran_stocks

No database founded.
creating database
making database folder ...
DataBase created in: C:\Users\user\tse
downloding  stock name and details from tccim
may take few minutes
Downloading group ids...
Add all groups, you can download stock price by following codes
from tehran_stocks import downloader
 downloader.download_all() # for downloading all data
downloader.download_group(group_id) # to download specefic group data
downloader.download_stock(stock) to downloand stock specefic
Stock table is available now, example:
from tehran_stocks import Stocks
stock =Stocks.query.filter_by(name="کگل").first()
Do you want to download all price? [y,(n)]y
Downloading price:
Download Finished.0.0%   total progress: 100.00%

In [6]:
from tehran_stocks import Stocks, db

In [24]:
db.session.query(Stocks.group_code, Stocks.group_name).group_by(Stocks.group_code).all()

[(10, 'استخراج زغال سنگ'),
 (11, 'استخراج نفت گاز و خدمات جنبي جز اکتشاف'),
 (13, 'استخراج کانه هاي فلزي'),
 (14, 'استخراج ساير معادن'),
 (17, 'منسوجات'),
 (19, 'دباغي، پرداخت چرم و ساخت انواع پاپوش'),
 (20, 'محصولات چوبي'),
 (21, 'محصولات كاغذي'),
 (22, 'انتشار، چاپ و تکثير'),
 (23, 'فراورده هاي نفتي، كك و سوخت هسته اي'),
 (25, 'لاستيك و پلاستيك'),
 (26, 'توليد محصولات كامپيوتري الكترونيكي ونوري'),
 (27, 'فلزات اساسي'),
 (28, 'ساخت محصولات فلزي'),
 (29, 'ماشين آلات و تجهيزات'),
 (31, 'ماشين آلات و دستگاه\u200cهاي برقي'),
 (32, 'ساخت دستگاه\u200cها و وسايل ارتباطي'),
 (33, 'ابزارپزشکي، اپتيکي و اندازه\u200cگيري'),
 (34, 'خودرو و ساخت قطعات'),
 (35, 'ساير تجهيزات حمل و نقل'),
 (38, 'قند و شكر'),
 (39, 'شرکتهاي چند رشته اي صنعتي'),
 (40, 'عرضه برق، گاز، بخاروآب گرم'),
 (42, 'محصولات غذايي و آشاميدني به جز قند و شكر'),
 (43, 'مواد و محصولات دارويي'),
 (44, 'محصولات شيميايي'),
 (45, 'پيمانكاري صنعتي'),
 (46, 'تجارت عمده فروشي به جز وسايل نقليه موتور'),
 (47, 'خرده فروشي،باستثناي وسايل نقليه موتوري'),
 (49, 'كاشي و سراميك'),
 (50, 'تجارت عمده وخرده فروشي وسائط نقليه موتور'),
 (51, 'حمل و نقل هوايي'),
 (52, 'انبارداري و حمايت از فعاليتهاي حمل و نقل'),
 (53, 'سيمان، آهك و گچ'),
 (54, 'ساير محصولات كاني غيرفلزي'),
 (55, 'هتل و رستوران'),
 (56, 'سرمايه گذاريها'),
 (57, 'بانكها و موسسات اعتباري'),
 (58, 'ساير واسطه گريهاي مالي'),
 (60, 'حمل ونقل، انبارداري و ارتباطات'),
 (61, 'حمل و نقل آبي'),
 (64, 'مخابرات'),
 (65, 'واسطه\u200cگري\u200cهاي مالي و پولي'),
 (66, 'بيمه وصندوق بازنشستگي به جزتامين اجتماعي'),
 (67, 'فعاليتهاي كمكي به نهادهاي مالي واسط'),
 (68, 'صندوق سرمايه گذاري قابل معامله'),
 (70, 'انبوه سازي، املاك و مستغلات'),
 (71, 'فعاليت مهندسي، تجزيه، تحليل و آزمايش فني'),
 (72, 'رايانه و فعاليت\u200cهاي وابسته به آن'),
 (73, 'اطلاعات و ارتباطات'),
 (74, 'خدمات فني و مهندسي'),
 (77, 'فعالبت هاي اجاره و ليزينگ'),
 (82, 'فعاليت پشتيباني اجرائي اداري وحمايت كسب'),
 (90, 'فعاليت هاي هنري، سرگرمي و خلاقانه')]

In [33]:
stock_list = Stocks.query.filter_by(group_code =13).all() # find all Stocks in Khodro

In [34]:
stock_list

[توسعه‌معادن‌وفلزات‌ (ومعادن) - بازار اول (تابلوي اصلي) بورس',FaraDesc ='-ومعادن-استخراج کانه هاي فلزي,
 توسعه معدني و صنعتي صبانور (كنور) - بازار دوم بورس',FaraDesc ='-كنور-استخراج کانه هاي فلزي,
 سنگ آهن شرق ايران (سنگ آهن شرق) - بازار سوم فرابورس',FaraDesc ='-سنگ آهن شرق-استخراج کانه هاي فلزي,
 توسعه‌ معادن‌ روي‌ ايران‌ (كروي) - بازار اول (تابلوي اصلي) بورس',FaraDesc ='-كروي-استخراج کانه هاي فلزي,
 معدني‌ دماوند (كدما) - بازار دوم بورس',FaraDesc ='-كدما-استخراج کانه هاي فلزي,
 فرآوري معدني اپال كاني پارس (اپال) - بازار دوم بورس',FaraDesc ='-اپال-استخراج کانه هاي فلزي,
 باما (كاما) - بازار اول (تابلوي اصلي) بورس',FaraDesc ='-كاما-استخراج کانه هاي فلزي,
 گروه صنعتي و معدني امير (وامير) - بازار پايه زرد فرابورس',FaraDesc ='قانون احکام دائمی برنامه های توسعه کشور-وامير-استخراج کانه هاي فلزي,
 سنگ آهن گهرزمين (كگهر) - بازار دوم فرابورس',FaraDesc ='-كگهر-استخراج کانه هاي فلزي,
 معدني‌وصنعتي‌چادرملو (كچاد) - بازار اول (تابلوي اصلي) بورس',FaraDesc ='-كچاد-استخراج کانه هاي فلزي,
 سرمايه گذاري صدرتامين (تاصيكو) - بازار دوم بورس',FaraDesc ='-تاصيكو-استخراج کانه هاي فلزي,
 سنگ آهن مرکزي (سنگ آهن) - بازار سوم فرابورس',FaraDesc ='-سنگ آهن-استخراج کانه هاي فلزي,
 آلوميناي ايران (آلومينا) - بازار سوم فرابورس',FaraDesc ='-آلومينا-استخراج کانه هاي فلزي,
 مجتمع معادن مس تكنار (تكنار) - بازار پايه زرد فرابورس',FaraDesc ='قانون احکام دائمی برنامه های توسعه کشور-تكنار-استخراج کانه هاي فلزي,
 معادن‌ بافق‌ (كبافق) - بازار دوم بورس',FaraDesc ='-كبافق-استخراج کانه هاي فلزي,
 معادن‌منگنزايران‌ (كمنگنز) - بازار دوم بورس',FaraDesc ='-كمنگنز-استخراج کانه هاي فلزي,
 معدني و صنعتي گل گهر (كگل) - بازار اول (تابلوي اصلي) بورس',FaraDesc ='-كگل-استخراج کانه هاي فلزي]

In [44]:
#stock = Stocks.query.filter_by(name='ومعادن').first() #find by symbol(نماد)
stock = Stocks.query.first()

In [52]:
stock.df.tail()

,id,code,ticker,dtyyyymmdd,date_shamsi,first,high,low,close,value,vol,openint,per,open,last
date,,,,,,,,,,,,,,,
2020-11-21,5,8977369674477111,Negin.Tabas.L.,20201121,1399/09/01,50770.0,50770.0,50770.0,50770.0,72406244740,1426162,520,D,48360.0,50770.0
2020-11-22,4,8977369674477111,Negin.Tabas.L.,20201122,1399/09/02,49500.0,53280.0,48240.0,51130.0,74558124860,1458290,1079,D,50770.0,49980.0
2020-11-23,3,8977369674477111,Negin.Tabas.L.,20201123,1399/09/03,51500.0,52500.0,48580.0,49950.0,61325904320,1227866,858,D,51130.0,49000.0
2020-11-24,2,8977369674477111,Negin.Tabas.L.,20201124,1399/09/04,49900.0,52440.0,47720.0,52060.0,183235962190,3520003,1184,D,49950.0,52440.0
2020-11-25,1,8977369674477111,Negin.Tabas.L.,20201125,1399/09/05,54000.0,54660.0,53000.0,54530.0,57244164020,1049698,468,D,52060.0,54660.0